const DisclaimerPage = () => {
  return (
    <div className="prose prose-lg max-w-none">
      <h1 className="text-4xl font-bold tracking-tight text-gray-900">
        DISCLAIMER
      </h1>
      <p className="text-sm text-gray-500">Last updated: December 3, 2025</p>

      <div className="mt-8">
        <p>
          This Disclaimer (&quot;Disclaimer&quot;) applies to all websites, applications, demo flows, telephony services, SMS tools, AI systems, and any other products or features operated by ReplyQuick LLC (&quot;ReplyQuick&quot;, &quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
        </p>
        <p className="mt-4">
          By accessing or using our Services, you acknowledge and agree to the terms of this Disclaimer. If you do not agree, please discontinue use of the Services.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          1. No Medical Advice or Professional Services
        </h2>
        <p>
          ReplyQuick provides AI-driven analysis, automated messaging, software tools, and demo environments for informational and operational purposes only.
        </p>
        <p className="mt-4">
          ReplyQuick does not provide medical, dental, clinical, legal, accounting, or professional advice.
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>AI outputs</li>
          <li>Automated reports</li>
          <li>Messages or notifications</li>
          <li>Demo reports</li>
          <li>Any information generated by the platform</li>
        </ul>
        <p className="mt-4">
          … do not constitute diagnosis, treatment, medical judgment, or professional recommendations of any kind.
        </p>
        <p className="mt-4">
          All clinical decisions must be made solely by licensed professionals.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          2. AI & Machine Learning Limitations
        </h2>
        <p>
          The Services may use artificial intelligence (AI), machine learning (ML), or automated analysis. These systems:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Are probabilistic</li>
          <li>May contain inaccuracies</li>
          <li>May produce incomplete or incorrect results</li>
          <li>May vary based on image quality, lighting, user input, and device type</li>
        </ul>
        <p className="mt-4">
          You agree not to rely solely on AI Output for clinical, medical, or safety-critical decisions.
        </p>
        <p className="mt-4">
          The Company disclaims all liability arising from reliance on any AI-generated output.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          3. Demo Mode & Non-Production Use
        </h2>
        <p>
          Demo environments and demo reports are provided solely for demonstration, evaluation, and educational purposes.
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Demo data is not reviewed by professionals</li>
          <li>Demo reports are not medical advice</li>
          <li>Demo links may expire or be modified at any time</li>
          <li>Demo submissions should not contain real patient information unless explicitly authorized under a signed BAA</li>
        </ul>
        <p className="mt-4">
          ReplyQuick is not responsible for decisions made based on demo outputs.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          4. No Guarantee of Accuracy or Availability
        </h2>
        <p>
          The Company does not warrant:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Accuracy</li>
          <li>Completeness</li>
          <li>Timeliness</li>
          <li>Reliability</li>
          <li>Compatibility</li>
          <li>Availability</li>
          <li>Error-free operation</li>
        </ul>
        <p className="mt-4">
          Of any content, data, analysis, or functionality.
        </p>
        <p className="mt-4">
          The Services may be interrupted for maintenance, technical failures, carrier outages, network issues, or reasons outside our control.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          5. External Links Disclaimer
        </h2>
        <p>
          The Services may contain links to third-party websites or tools.
        </p>
        <p className="mt-4">
          ReplyQuick does not:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Monitor</li>
          <li>Control</li>
          <li>Endorse</li>
          <li>Guarantee</li>
        </ul>
        <p className="mt-4">
          …any third-party information.
        </p>
        <p className="mt-4">
          You access these external websites at your own risk.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          6. SMS, 10DLC, and Messaging Disclaimer
        </h2>
        <p>
          ReplyQuick provides messaging and telephony features that rely on:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Third-party carriers</li>
          <li>Aggregators</li>
          <li>Gateways</li>
          <li>APIs</li>
          <li>Telecommunications infrastructure</li>
        </ul>
        <p className="mt-4">
          We do not guarantee message delivery, timeliness, or accuracy.
        </p>
        <p className="mt-4">
          Carrier filtering, outages, or restrictions may affect message transmission.
        </p>
        <p className="mt-4">
          The Company is not responsible for:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Undelivered messages</li>
          <li>Duplicated messages</li>
          <li>Delays caused by carriers</li>
          <li>Incorrect numbers provided by users</li>
          <li>Spam filtering applied by networks</li>
        </ul>
        <p className="mt-4">
          You assume full responsibility for complying with all SMS opt-in and messaging regulations.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          7. User Responsibility
        </h2>
        <p>
          You agree that:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>You will not rely on the Services for emergency or urgent care</li>
          <li>You will not upload harmful, unlawful, or misleading data</li>
          <li>You will verify AI outputs before using them professionally</li>
          <li>You are solely responsible for decisions made using the Services</li>
          <li>You will ensure compliance with applicable laws and regulations</li>
        </ul>
        <p className="mt-4">
          ReplyQuick is not responsible for any errors, omissions, misinterpretations, or misuse of the Services.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          8. Limitation of Liability
        </h2>
        <p>
          To the fullest extent permitted by law:
        </p>
        <p className="mt-4">
          ReplyQuick LLC, its employees, officers, contractors, affiliates, and partners shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including but not limited to:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Medical decisions</li>
          <li>Loss of profits or revenue</li>
          <li>Loss of data</li>
          <li>Failure to diagnose</li>
          <li>Wrongful reliance on AI outputs</li>
          <li>Business interruption</li>
          <li>Damages caused by telephony, messaging, or carriers</li>
          <li>Errors in demo mode</li>
          <li>Delays or downtime</li>
        </ul>
        <p className="mt-4">
          Even if advised of the possibility of such damages.
        </p>
        <p className="mt-4">
          All information is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          9. No Client–Professional Relationship
        </h2>
        <p>
          Use of the Services does not create:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Dentist–patient relationship</li>
          <li>Doctor–patient relationship</li>
          <li>Consultant–client relationship</li>
          <li>Professional engagement of any kind</li>
        </ul>
        <p className="mt-4">
          ReplyQuick is a technology platform only.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          10. Changes to This Disclaimer
        </h2>
        <p>
          We reserve the right to update or modify this Disclaimer at any time.
        </p>
        <p className="mt-4">
          The &quot;Last updated&quot; date will be updated accordingly.
        </p>
        <p className="mt-4">
          Your continued use of the Services indicates acceptance of those changes.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          11. Contact Us
        </h2>
        <p>
          If you have questions about this Disclaimer, contact:
        </p>
        <p className="mt-4">
          ReplyQuick LLC
        </p>
        <p>
          Email:{" "}
          <a
            href="mailto:info@replyquick.ai"
            className="text-blue-600 hover:underline"
          >
            info@replyquick.ai
          </a>
        </p>
      </div>
    </div>
  );
};

export default DisclaimerPage;