-- demo_patient (matches Prisma field names)
CREATE TABLE IF NOT EXISTS PUBLIC.DEMO_PATIENT (
  ID TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  PHONE TEXT NOT NULL,
  EMAIL TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "dentistId" TEXT NOT NULL REFERENCES PUBLIC.DEMO_DENTIST(ID) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS DEMO_PATIENT_DENTISTID_IDX ON PUBLIC.DEMO_PATIENT("dentistId");

-- demo_scan (matches Prisma field names)
CREATE TABLE IF NOT EXISTS PUBLIC.DEMO_SCAN (
  ID TEXT PRIMARY KEY,
  STATUS TEXT NOT NULL DEFAULT 'link_sent',
  "imageUrls" JSONB,
  RESULT JSONB,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "submittedAt" TIMESTAMPTZ,
  "completedAt" TIMESTAMPTZ,
  "dentistId" TEXT REFERENCES PUBLIC.DEMO_DENTIST(ID) ON DELETE SET NULL,
  "patientId" TEXT REFERENCES PUBLIC.DEMO_PATIENT(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS DEMO_SCAN_DENTISTID_IDX ON PUBLIC.DEMO_SCAN("dentistId");

CREATE INDEX IF NOT EXISTS DEMO_SCAN_PATIENTID_IDX ON PUBLIC.DEMO_SCAN("patientId");

-- demo_scan_link (matches Prisma field names)
CREATE TABLE IF NOT EXISTS PUBLIC.DEMO_SCAN_LINK (
  ID TEXT PRIMARY KEY,
  CODE TEXT NOT NULL UNIQUE,
  "scanId" TEXT NOT NULL REFERENCES PUBLIC.DEMO_SCAN(ID) ON DELETE CASCADE,
  "dentistId" TEXT,
  "patientId" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "expiresAt" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS DEMO_SCAN_LINK_SCANID_IDX ON PUBLIC.DEMO_SCAN_LINK("scanId");

-- PartnerWithUs (mapped table name is "PartnerWithUs" in Prisma)
CREATE TABLE IF NOT EXISTS PUBLIC."PartnerWithUs" (
  ID TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  ORGANIZATION TEXT,
  TYPE TEXT NOT NULL,
  MESSAGE TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);