const TermsAndConditionsPage = () => {
  return (
    <div className="prose prose-lg max-w-none">
      <h1 className="text-4xl font-bold tracking-tight text-gray-900">
        TERMS & CONDITIONS (TERMS OF SERVICE)
      </h1>
      <p className="text-sm text-gray-500">Last updated: December 3, 2025</p>

      <div className="mt-8">
        <p>
          These Terms & Conditions (&quot;Terms&quot;) constitute a binding agreement between ReplyQuick LLC (&quot;the Company&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;) and you (&quot;you&quot;, &quot;your&quot;, &quot;User&quot;, &quot;Clinic&quot;, &quot;Dentist&quot;, &quot;Patient&quot;, or &quot;Visitor&quot;). By accessing or using any ReplyQuick service, you agree to be bound by these Terms. If you do not agree, do not access or use our services.
        </p>
        <p className="mt-4">
          These Terms apply to all versions of the ReplyQuick platform, including:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>DentalScan</li>
          <li>ReplyQuick AI voice/text systems</li>
          <li>Demo and sandbox flows</li>
          <li>Websites, dashboards, and mobile interfaces</li>
          <li>Machine learning outputs</li>
          <li>Messaging, telephony, and 10DLC services</li>
          <li>Any linked tools or features</li>
        </ul>
        <p className="mt-4">
          If you enter into a Business Associate Agreement (BAA) or DPA with us, those documents govern your privacy and data handling and supplement—but do not replace—these Terms.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          1. Definitions
        </h2>
        <p>
          &quot;Services&quot; means all websites, dashboards, AI systems, messaging systems, and related products provided by ReplyQuick.
        </p>
        <p className="mt-4">
          &quot;Clinic&quot; means a dental practice or health organization onboarding to the platform.
        </p>
        <p className="mt-4">
          &quot;Demo Flow&quot; means the non-production interface used for investors, schools, gyms, charities, or general demonstration.
        </p>
        <p className="mt-4">
          &quot;PHI&quot; means Protected Health Information under HIPAA/HITECH.
        </p>
        <p className="mt-4">
          &quot;User Data&quot; means any information you provide through the Services.
        </p>
        <p className="mt-4">
          &quot;AI Output&quot; means analysis, predictions, classifications, or reports generated by machine learning models.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          2. Eligibility
        </h2>
        <p>
          To use the Services, you must:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Be at least 18 years old</li>
          <li>Have legal authority to bind a Clinic (if signing for a practice)</li>
          <li>Agree to comply with all applicable laws</li>
        </ul>
        <p className="mt-4">
          Clinics must designate a single compliance contact responsible for accurate data submission.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          3. Nature of the Services
        </h2>
        <p>
          ReplyQuick provides:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>AI-driven dental imaging analysis</li>
          <li>Missed-call recovery systems</li>
          <li>Automated SMS and voice agents</li>
          <li>Scheduling integrations</li>
          <li>Telehealth workflows</li>
          <li>Data export and deletion tools</li>
          <li>Demo environments for non-clinical use</li>
        </ul>
        <p className="mt-4">
          We do not provide medical diagnosis, treatment, or prescriptions.
        </p>
        <p className="mt-4">
          AI Output is informational only.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          4. Machine Learning Output Disclaimer
        </h2>
        <p>
          AI Output is:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Not a replacement for a licensed clinician</li>
          <li>Not definitive medical advice</li>
          <li>Based on probabilistic algorithms</li>
          <li>Subject to error due to image quality, user input, lighting, camera type, and environmental variables</li>
        </ul>
        <p className="mt-4">
          Clinics must review all AI Output before using it for clinical decision-making.
        </p>
        <p className="mt-4">
          ReplyQuick disclaims liability for:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Misdiagnosis</li>
          <li>Patient injury</li>
          <li>Incorrect treatment plans</li>
          <li>Reliance on AI Output without clinical review</li>
        </ul>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          5. HIPAA, PHI, and Data Protection
        </h2>
        <p>
          ReplyQuick maintains HIPAA-compliant infrastructure, including:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Encryption at rest and in transit</li>
          <li>Access controls</li>
          <li>Audit logs</li>
          <li>Secure storage</li>
          <li>Signed BAAs</li>
        </ul>
        <p className="mt-4">
          Clinics must not upload PHI until their BAA is signed and compliance region is verified.
        </p>
        <p className="mt-4">
          Patients using Demo Flow must not upload real medical data unless the receiving Clinic has an active BAA.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          6. Demo Flow
        </h2>
        <p>
          Demo Flow is intended for:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Dentists evaluating the product</li>
          <li>Investors reviewing functionality</li>
          <li>Schools, gyms, charities, or partners gathering test data</li>
        </ul>
        <p className="mt-4">
          Demo Flow:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>May store data for dataset improvement</li>
          <li>Should not be used for real clinical decision-making</li>
          <li>May limit PHI features depending on compliance</li>
        </ul>
        <p className="mt-4">
          ReplyQuick retains the right to delete Demo data at any time.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          7. Data Collection & Data Rights
        </h2>
        <p>
          By using the Services, you authorize ReplyQuick to:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Collect, process, and store data for operational purposes</li>
          <li>Retain de-identified data for ML model improvement</li>
          <li>Use anonymized data for statistical, analytical, and training purposes</li>
        </ul>
        <p className="mt-4">
          PHI is handled according to your signed BAA.
        </p>
        <p className="mt-4">
          Non-PHI data is handled according to our Privacy Policy.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          8. Data Export & Deletion
        </h2>
        <p>
          Clinics may request:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Data exports</li>
          <li>Data deletion (after the legally required retention period)</li>
        </ul>
        <p className="mt-4">
          Exports remain available for a limited time.
        </p>
        <p className="mt-4">
          Some data may be retained in audit logs to comply with HIPAA/HITECH.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          9. SMS, 10DLC, and Messaging Compliance
        </h2>
        <p>
          By using SMS or voice features, you agree to:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Obtain proper opt-in from recipients</li>
          <li>Follow 10DLC, CTIA, and carrier requirements</li>
          <li>Not upload purchased, scraped, or unverified numbers</li>
          <li>Not use messaging features for spam or prohibited content</li>
        </ul>
        <p className="mt-4">
          Failure to comply may result in immediate termination.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          10. Payments and Subscriptions
        </h2>
        <p>
          If your Clinic purchases a subscription:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Fees are billed monthly or annually</li>
          <li>Payments are non-refundable unless required by law</li>
          <li>Late or failed payments may result in suspension</li>
          <li>Discounts, promotions, and credits are not guaranteed</li>
        </ul>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          11. Intellectual Property
        </h2>
        <p>
          ReplyQuick owns:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>The platform</li>
          <li>ML models</li>
          <li>UI/UX</li>
          <li>Workflows</li>
          <li>Documentation</li>
          <li>Logos, branding, and trademarks</li>
          <li>All derivative works</li>
        </ul>
        <p className="mt-4">
          You may not:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Copy</li>
          <li>Reverse-engineer</li>
          <li>Modify</li>
          <li>Scrape</li>
          <li>Redistribute</li>
        </ul>
        <p className="mt-4">
          Any part of the Services without written permission.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          12. Prohibited Uses
        </h2>
        <p>
          You agree NOT to use the Services for:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Unauthorized medical diagnosis</li>
          <li>Fraudulent activity</li>
          <li>Scraping or data extraction</li>
          <li>Selling or sharing SMS opt-in data</li>
          <li>Misrepresenting identity</li>
          <li>Uploading harmful or illegal content</li>
        </ul>
        <p className="mt-4">
          Violations may result in termination and legal action.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          13. Limitation of Liability
        </h2>
        <p>
          ReplyQuick is not liable for:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>Damages arising from reliance on AI Output</li>
          <li>Loss of data</li>
          <li>Delays due to carrier networks</li>
          <li>Indirect, incidental, or consequential damages</li>
          <li>Downtime, outages, or maintenance</li>
          <li>Incorrect user input</li>
          <li>Demo Flow misuse</li>
          <li>Third-party integrations (Twilio, Supabase, etc.)</li>
        </ul>
        <p className="mt-4">
          Maximum liability is limited to fees paid in the previous 6 months.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          14. Termination
        </h2>
        <p>
          We may suspend or terminate your access if:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li>You violate these Terms</li>
          <li>You violate HIPAA or 10DLC rules</li>
          <li>You misuse messaging systems</li>
          <li>You misuse Demo Flow</li>
          <li>Your Clinic fails to pay</li>
          <li>You upload prohibited content</li>
        </ul>
        <p className="mt-4">
          Upon termination, certain data may be retained for compliance.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          15. Governing Law
        </h2>
        <p>
          These Terms are governed by the laws of the State of Florida, without regard to conflict of law principles.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          16. Changes to These Terms
        </h2>
        <p>
          We may update these Terms at any time.
        </p>
        <p className="mt-4">
          Continued use of the Services indicates acceptance of updated Terms.
        </p>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900">
          17. Contact Us
        </h2>
        <p>
          ReplyQuick LLC
        </p>
        <p>
          Venice, Florida
        </p>
        <p>
          <a
            href="mailto:info@replyquick.ai"
            className="text-blue-600 hover:underline"
          >
            info@replyquick.ai
          </a>
        </p>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;